/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  openApiSidebar: [
//    {
//      type: "category",
//      label: "Petstore",
//      link: {
//        type: "generated-index",
//        title: "Petstore API",
//        description:
//          "This is a sample server Petstore server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
//        slug: "/category/petstore-api"
//      },
//      // @ts-ignore
//      items: require("./docs/petstore/sidebar.js")
//    },
        {
          type: "category",
          label: "API",

          link: {
            type: "generated-index",
            title: "Linguagens API",
            description:
              `<!DOCTYPE html>
              <html>
              
              <head>
                  <style type="text/css">
                      hr {
                          width: 50%;
                          height: 20px;
                          background-color: red;
                          margin-right: auto;
                          margin-left: auto;
                          margin-top: 5px;
                          margin-bottom: 5px;
                          border-width: 2px;
                          border-color: green;
                      }
                  </style>
              </head>
              
              <body>
                  <h1>Bem-vindo(a)! </h1>
                  <hr>
                  <p1>Isto é um parágrafo separado por uma linha horizontal </p1>
              </body>
              
              </html>`,
            slug: "/category/linguagens-api"
          },
          // @ts-ignore
          items: require("./docs/linguagens/sidebar.js")
        }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
